name: 🍏 macOS

on: [push, pull_request]

jobs:
# TODO: (old Travis-CI coverage)
#  appleclang9_py37_nompi_h5_ad1
#  appleclang10_py37_h5_ad2_libcpp
#  appleclang11_nopy_nompi_h5_ad2

  appleclang12_py_mpi_h5_ad2:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        rm -rf /usr/local/bin/2to3
        set +e
        brew update
        brew install adios2 || true
        brew install hdf5-mpi || true
        brew install python || true
        set -e
        # Install Julia
        wget https://julialang-s3.julialang.org/bin/mac/x64/1.6/julia-1.6.2-mac64.dmg
        sudo hdiutil attach julia-1.6.2-mac64.dmg
        sudo cp -fr /Volumes/Julia-1.6.2/Julia-1.6.app /Applications
        sudo hdiutil detach /Volumes/Julia-1.6.2
        rm julia-1.6.2-mac64.dmg
        # Install libcxxwrap-julia
        wget https://github.com/JuliaInterop/libcxxwrap-julia/archive/refs/tags/v0.8.3.tar.gz
        tar xzf v0.8.3.tar.gz
        cd libcxxwrap-julia-0.8.3
        cmake -S . -B build
        cmake --build build --parallel 2
        cmake --install build --parallel 2
    - name: Build
      env: {CXXFLAGS: -Werror -Wno-deprecated-declarations, MACOSX_DEPLOYMENT_TARGET: 10.9}
      # C++11 & 14 support in macOS 10.9+
      # C++17 support in macOS 10.13+/10.14+
      #   https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#macos-and-deployment-target-versions
      run: |
        share/openPMD/download_samples.sh build
        chmod u-w build/samples/git-sample/*.h5
        cmake -S . -B build \
          -DopenPMD_USE_ADIOS2=ON \
          -DopenPMD_USE_HDF5=ON   \
          -DopenPMD_USE_Julia=ON  \
          -DopenPMD_USE_MPI=ON    \
          -DopenPMD_USE_PYTHON=ON \
          -DopenPMD_USE_INVASIVE_TESTS=ON
        cmake --build build --parallel 2
        ctest --test-dir build --output-on-failure

# TODO: apple_conda_ompi_all (similar to conda_ompi_all on Linux)
#   both OpenMPI and MPICH cause startup (MPI_Init) issues on GitHub Actions
